package main

func main() {

	panic("exception")
}
